export interface Information {
  id: string;
  title: string;
  writer: string;
  date: string;
  view: number;
  like: number;
}
export const informations: Information[] = [
  {
    id: '1',
    title: '고혈압이 있다면? 고혈압 환자 운동시 주의사항',
    writer: '관리자',
    date: '2024-05-30',
    view: 21,
    like: 20,
  },
  {
    id: '2',
    title: '스포츠심리학 : 최고의 멘탈 조성을 위한 일반적 지침',
    writer: '관리자',
    date: '2024-05-29',
    view: 21,
    like: 20,
  },
  {
    id: '3',
    title: '신체활동 저하로 인해 생기는 변화와 신체활동의 중요성',
    writer: '관리자',
    date: '2024-05-28',
    view: 21,
    like: 20,
  },
  {
    id: '4',
    title: '100세시대 건강하게 장수하자! 앉아서 하는 전신운동',
    writer: '관리자',
    date: '2024-05-27',
    view: 21,
    like: 20,
  },
  {
    id: '5',
    title: '어린이 비만 걱정하지 마세요, 줄넘기로 해결돼요.',
    writer: '관리자',
    date: '2024-05-26',
    view: 21,
    like: 20,
  },
  {
    id: '6',
    title: '잘못된 다이어트 식단, 탈모 유발의 원인?!',
    writer: '관리자',
    date: '2024-05-25',
    view: 21,
    like: 20,
  },
  {
    id: '7',
    title: '감기 걸렸을 때 운동해도 될까요?',
    writer: '관리자',
    date: '2024-05-24',
    view: 21,
    like: 20,
  },
  {
    id: '8',
    title: '정말로 술을 마시고 난 다음날 운동은 위험할까?',
    writer: '관리자',
    date: '2024-05-23',
    view: 21,
    like: 20,
  },
  {
    id: '9',
    title: '콜레스테롤 잡는 3가지 관리 방법',
    writer: '관리자',
    date: '2024-05-22',
    view: 21,
    like: 20,
  },
  {
    id: '10',
    title: '거북목 & 굽은등 교정방법?',
    writer: '관리자',
    date: '2024-05-21',
    view: 21,
    like: 20,
  },
  {
    id: '11',
    title: '뱃살 빼는 6가지 운동',
    writer: '관리자',
    date: '2024-05-20',
    view: 21,
    like: 20,
  },
  {
    id: '12',
    title: '운동 시 충분한 수분섭취가 중요한 이유',
    writer: '관리자',
    date: '2024-05-19',
    view: 21,
    like: 20,
  },
  {
    id: '13',
    title: '초보자를 위한 전신 운동 가이드',
    writer: '관리자',
    date: '2024-05-18',
    view: 21,
    like: 20,
  },
  {
    id: '14',
    title: '무릎이 안좋다면 수영을!',
    writer: '관리자',
    date: '2024-05-17',
    view: 35,
    like: 21,
  },
  {
    id: '15',
    title: '점핑 다이어트의 효능',
    writer: '관리자',
    date: '2024-05-16',
    view: 11,
    like: 10,
  },
  {
    id: '16',
    title: '개인 필라테스 VS 그룹 필라테스',
    writer: '관리자',
    date: '2024-05-15',
    view: 21,
    like: 20,
  },
];
