spring:
  profiles:
    active: blue
    group:
      local: local, common, secret
      blue: blue, common, secret
      green: green, common, secret

server:
  env: blue

---

spring:
  config:
    activate:
      on-profile: local
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: "http://localhost:8080/api/auth/google"
          naver:
            redirect-uri: "http://localhost:8080/api/auth/naver/callback"
          kakao:
            redirect-uri: "http://localhost:8080/api/auth/kakao/callback"

server:
  port: 8080
  serverAddress: localhost

serverName: local_server

---

spring:
  config:
    activate:
      on-profile: blue
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: "http://43.202.9.153/api/auth/google"
          naver:
            redirect-uri: "http://43.202.9.153/api/auth/naver/callback"
          kakao:
            redirect-uri: "http://43.202.9.153/api/auth/kakao/callback"

server:
  port: 8080
  serverAddress: 43.202.9.153

serverName: blue_server

---

spring:
  config:
    activate:
      on-profile: green
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: "http://43.202.9.153/api/auth/google"
          naver:
            redirect-uri: "http://43.202.9.153/api/auth/naver/callback"
          kakao:
            redirect-uri: "http://43.202.9.153/api/auth/kakao/callback"

server:
  port: 8081
  serverAddress: 43.202.9.153

serverName: green_server

---

spring:
  config:
    activate:
      on-profile: common

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# mybatis
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  config-location: classpath:mybatis-config.xml

# logging
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.spring.myapp: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  file:
    name: logs/myapp.log