import image02 from '../assets/img/image02.jpg';
import image03 from '../assets/img/image03.jpg';
import image04 from '../assets/img/image04.jpg';
import image05 from '../assets/img/image05.jpg';
import image06 from '../assets/img/image06.jpg';
import image08 from '../assets/img/image08.jpg';
import image09 from '../assets/img/image09.jpg';
import image14 from '../assets/img/image14.jpg';

export interface Product {
  id: number;
  category: string;
  name: string;
  price: number;
  discountRate: number;
  description?: string;
  sales: number;
  likes: number;
  imageUrl: string;
}

export const productData: Product[] = [
  {
    id: 1,
    category: '운동용품',
    name: 'ABC 악력기',
    price: 17000,
    discountRate: 10,
    description: '상품 1에 대한 설명입니다.',
    sales: 50,
    likes: 5,
    imageUrl: image03,
  },
  {
    id: 2,
    category: '운동용품',
    name: '상품 2',
    price: 20000,
    discountRate: 20,
    description: '상품 2에 대한 설명입니다.',
    sales: 30,
    likes: 10,
    imageUrl: image03,
  },
  {
    id: 3,
    category: '운동용품',
    name: '상품 3',
    price: 10000,
    discountRate: 10,
    description: '상품 3에 대한 설명입니다.',
    sales: 30,
    likes: 10,
    imageUrl: image03,
  },
  {
    id: 4,
    category: '운동용품',
    name: '상품 4',
    price: 80000,
    discountRate: 40,
    description: '상품 4에 대한 설명입니다.',
    sales: 6,
    likes: 100,
    imageUrl: image03,
  },
  {
    id: 5,
    category: '운동용품',
    name: '상품 5',
    price: 50000,
    discountRate: 10,
    description: '상품 5에 대한 설명입니다.',
    sales: 30,
    likes: 10,
    imageUrl: image02,
  },
  {
    id: 6,
    category: '운동용품',
    name: '상품 6',
    price: 70000,
    discountRate: 10,
    description: '상품 6에 대한 설명입니다.',
    sales: 30,
    likes: 10,
    imageUrl: image02,
  },
  {
    id: 7,
    category: '운동용품',
    name: '상품 7',
    price: 50000,
    discountRate: 10,
    description: '상품 7에 대한 설명입니다.',
    sales: 30,
    likes: 10,
    imageUrl: image02,
  },
  {
    id: 8,
    category: '운동용품',
    name: '상품 8',
    price: 80000,
    discountRate: 10,
    description: '상품 8에 대한 설명입니다.',
    sales: 30,
    likes: 10,
    imageUrl: image02,
  },
  {
    id: 9,
    category: '운동용품',
    name: '상품 9',
    price: 10000,
    discountRate: 10,
    description: '상품 9에 대한 설명입니다.',
    sales: 50,
    likes: 5,
    imageUrl: image04,
  },
  {
    id: 10,
    category: '운동용품',
    name: '상품 10',
    price: 20000,
    discountRate: 20,
    description: '상품 10에 대한 설명입니다.',
    sales: 30,
    likes: 10,
    imageUrl: image04,
  },
  {
    id: 11,
    category: '운동용품',
    name: '상품 11',
    price: 10000,
    discountRate: 10,
    description: '상품 11에 대한 설명입니다.',
    sales: 30,
    likes: 10,
    imageUrl: image04,
  },
  {
    id: 12,
    category: '운동용품',
    name: '상품 12',
    price: 80000,
    discountRate: 40,
    description: '상품 12에 대한 설명입니다.',
    sales: 6,
    likes: 100,
    imageUrl: image04,
  },
  {
    id: 13,
    category: '운동용품',
    name: '상품 13',
    price: 23000,
    discountRate: 10,
    description: '상품 13에 대한 설명입니다.',
    sales: 71,
    likes: 500,
    imageUrl: image05,
  },
  {
    id: 14,
    category: '운동용품',
    name: '상품 14',
    price: 23000,
    discountRate: 10,
    description: '상품 14에 대한 설명입니다.',
    sales: 71,
    likes: 500,
    imageUrl: image05,
  },
  {
    id: 15,
    category: '운동용품',
    name: '상품 15',
    price: 23000,
    discountRate: 10,
    description: '상품 15에 대한 설명입니다.',
    sales: 71,
    likes: 500,
    imageUrl: image05,
  },
  {
    id: 16,
    category: '운동용품',
    name: '상품 16',
    price: 23000,
    discountRate: 10,
    description: '상품 16에 대한 설명입니다.',
    sales: 71,
    likes: 500,
    imageUrl: image05,
  },
  {
    id: 17,
    category: '보충제',
    name: '비타민 365',
    price: 17000,
    discountRate: 10,
    description: '상품 17에 대한 설명입니다.',
    sales: 50,
    likes: 5,
    imageUrl: image09,
  },
  {
    id: 18,
    category: '보충제',
    name: '상품 18',
    price: 20000,
    discountRate: 20,
    description: '상품 18에 대한 설명입니다.',
    sales: 30,
    likes: 10,
    imageUrl: image09,
  },
  {
    id: 19,
    category: '보충제',
    name: '상품 19',
    price: 10000,
    discountRate: 10,
    description: '상품 19에 대한 설명입니다.',
    sales: 30,
    likes: 10,
    imageUrl: image09,
  },
  {
    id: 20,
    category: '보충제',
    name: '상품 20',
    price: 80000,
    discountRate: 40,
    description: '상품 20에 대한 설명입니다.',
    sales: 6,
    likes: 100,
    imageUrl: image09,
  },
  {
    id: 21,
    category: '보충제',
    name: '비타민 365',
    price: 17000,
    discountRate: 10,
    description: '상품 21에 대한 설명입니다.',
    sales: 50,
    likes: 5,
    imageUrl: image06,
  },
  {
    id: 22,
    category: '보충제',
    name: '비타민 365',
    price: 17000,
    discountRate: 10,
    description: '상품 22에 대한 설명입니다.',
    sales: 50,
    likes: 5,
    imageUrl: image06,
  },
  {
    id: 23,
    category: '보충제',
    name: '비타민 365',
    price: 17000,
    discountRate: 10,
    description: '상품 23에 대한 설명입니다.',
    sales: 50,
    likes: 5,
    imageUrl: image06,
  },
  {
    id: 24,
    category: '보충제',
    name: '비타민 365',
    price: 17000,
    discountRate: 10,
    description: '상품 24에 대한 설명입니다.',
    sales: 50,
    likes: 5,
    imageUrl: image06,
  },
  {
    id: 25,
    category: '보충제',
    name: '비타민 365',
    price: 17000,
    discountRate: 10,
    description: '상품 25에 대한 설명입니다.',
    sales: 50,
    likes: 5,
    imageUrl: image08,
  },
  {
    id: 26,
    category: '보충제',
    name: '상품 26',
    price: 20000,
    discountRate: 20,
    description: '상품 26에 대한 설명입니다.',
    sales: 30,
    likes: 10,
    imageUrl: image08,
  },
  {
    id: 27,
    category: '보충제',
    name: '상품 27',
    price: 10000,
    discountRate: 10,
    description: '상품 27에 대한 설명입니다.',
    sales: 30,
    likes: 10,
    imageUrl: image08,
  },
  {
    id: 28,
    category: '보충제',
    name: '상품 28',
    price: 80000,
    discountRate: 40,
    description: '상품 28에 대한 설명입니다.',
    sales: 6,
    likes: 100,
    imageUrl: image08,
  },
  {
    id: 29,
    category: '식품',
    name: 'ABC 악력기',
    price: 17000,
    discountRate: 10,
    description: '상품 29에 대한 설명입니다.',
    sales: 50,
    likes: 5,
    imageUrl: image14,
  },
  {
    id: 30,
    category: '식품',
    name: '상품 2',
    price: 20000,
    discountRate: 20,
    description: '상품 30에 대한 설명입니다.',
    sales: 30,
    likes: 10,
    imageUrl: image14,
  },
  {
    id: 31,
    category: '식품',
    name: '상품 3',
    price: 10000,
    discountRate: 10,
    description: '상품 31에 대한 설명입니다.',
    sales: 30,
    likes: 10,
    imageUrl: image14,
  },
  {
    id: 32,
    category: '식품',
    name: '상품 4',
    price: 80000,
    discountRate: 40,
    description: '상품 32에 대한 설명입니다.',
    sales: 6,
    likes: 100,
    imageUrl: image14,
  },
  {
    id: 33,
    category: '식품',
    name: 'ABC 악력기',
    price: 17000,
    discountRate: 10,
    description: '상품 33에 대한 설명입니다.',
    sales: 50,
    likes: 5,
    imageUrl: image14,
  },
  {
    id: 34,
    category: '식품',
    name: '상품 2',
    price: 20000,
    discountRate: 20,
    description: '상품 34에 대한 설명입니다.',
    sales: 30,
    likes: 10,
    imageUrl: image14,
  },
  {
    id: 35,
    category: '식품',
    name: '상품 3',
    price: 10000,
    discountRate: 10,
    description: '상품 35에 대한 설명입니다.',
    sales: 30,
    likes: 10,
    imageUrl: image14,
  },
  {
    id: 36,
    category: '식품',
    name: '상품 4',
    price: 80000,
    discountRate: 40,
    description: '상품 36에 대한 설명입니다.',
    sales: 6,
    likes: 100,
    imageUrl: image14,
  },
];
